display-name = "Trần Đức Nam"
signature = "Trân trọng cảm ơn,"
email-listing-page-size = 50

[personal]
default = true
email = "me@dynamotn.dev"
downloads-dir = "~/Misc/Emails/personal"
sync = true

backend = "imap"
imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "me@dynamotn.dev"
imap-auth = "passwd"
imap-starttls = true
imap-insecure = true
imap-passwd = { cmd = "cat ~/.local/share/himalaya/personal-passwd" }

sender = "smtp"
smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "me@dynamotn.dev"
smtp-auth = "passwd"
smtp-starttls = true
smtp-insecure = true
smtp-passwd = { cmd = "cat ~/.local/share/himalaya/personal-passwd" }

[personal.folder-aliases]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"
