display-name = "Trần Đức Nam"
signature = "Trân trọng cảm ơn,"

[accounts.personal]
default = true
email = "me@dynamotn.dev"
downloads-dir = "~/Misc/Emails/personal"
sync = true

folder.aliases.inbox = "INBOX"
folder.aliases.sent = "Sent"
folder.aliases.drafts = "Drafts"
folder.aliases.trash = "Trash"

backend.type = "imap"
backend.host = "10.200.1.194"
backend.port = 143
backend.encryption.type = "start-tls"
backend.login = "me@dynamotn.dev"
backend.auth.type = "password"
backend.auth.cmd = "rbw get 'Proton' --field 'Pass via IMAP bridge'"

message.send.backend.type = "smtp"
message.send.backend.host = "10.200.1.194"
message.send.backend.port = 25
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "me@dynamotn.dev"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "rbw get 'Proton' --field 'Pass via IMAP bridge'"
