# Mode
Mode="Uinput (Smooth)"
# Input Method
InputMethod=Telex
# Output Charset
OutputCharset=Unicode
# Cycle Mode Hotkey
CycleModeKey=
# Type w to Produce ư
W2U=Non-Start
# Type [ -> ơ, ] -> ư, { -> Ơ, } -> Ư
BracketTransform=Disabled
# Enable Spell Check Using Dictionary
SpellCheck=True
# Enable Macro
EnableMacro=True
# Capitalize Macro
CapitalizeMacro=True
# Modifier to Skip Macro for Next Word
MacroSkipTriggerModifier=Disabled
# Auto capitalize after sentence-ending punctuation (. ! ? Enter)
AutoCapitalizeAfterPunctuation=False
# Double Space to Period
DoubleSpaceToPeriod=False
# Double Hyphen to Em-Dash (--)
DoubleHyphenToEmDash=False
# Auto Restore Invalid Words
AutoNonVnRestore=True
# Use oà, uý (Instead Of òa, úy)
ModernStyle=True
# Allow Type With More Freedom
FreeMarking=True
# Allow dd To Produce đ When Auto Restore Invalid Words Is On
DdFreeStyle=True
# Fix Uinput Mode With Ack
FixUinputWithAck=False
# Use Lotus Status Icons
UseLotusIcons=False
# Custom Dictionary
EnableDictionary=False
# Custom Keymap
EnableCustomKeymap=False
# Show Uinput (Smooth)
ShowModeSmooth=True
# Shortcut for Uinput (Smooth)
ShortcutSmooth=1
# Show Uinput (Slow)
ShowModeUinput=True
# Shortcut for Uinput (Slow)
ShortcutUinput=2
# Show Uinput (Super Smooth)
ShowModeSuperSmooth=True
# Shortcut for Uinput (Super Smooth)
ShortcutSuperSmooth=a
# Show Minecraft
ShowModeMinecraft=True
# Shortcut for Minecraft
ShortcutMinecraft=3
# Show Surrounding Text
ShowModeSurroundingText=True
# Shortcut for Surrounding Text
ShortcutSurroundingText=4
# Show Preedit
ShowModePreedit=True
# Shortcut for Preedit
ShortcutPreedit=q
# Show Emoji Picker
ShowModeEmoji=True
# Shortcut for Emoji Picker
ShortcutEmoji=w
# Show OFF
ShowModeOff=True
# Shortcut for OFF
ShortcutOff=e
# Show Default Typing
ShowModeDefault=True
# Shortcut for Default Typing
ShortcutDefault=r
# Allow Macro in Off Mode
EnableMacroInOffMode=False
# Use Surrounding Text if possible
useSurroundingTextIfPossible=False
# Mode Order
ModeOrder=Smooth,Uinput,Minecraft,SurroundingText,Preedit,Emoji,Off,SuperSmooth,Default
# Time Format ($TIME in macro)
TimeFormat=%H:%M
# Date Format ($DATE in macro)
DateFormat=%d/%m/%Y
# Icon Color
IconTheme=Auto

[ModeMenuKey]
0=grave
