#!/usr/bin/env bash
export CONFIG_DIR=~/.config/sketchybar
################################################################################
# Catpuccin Machiatto Theme
################################################################################
source "${CONFIG_DIR}/themes/catppuccin.sh"

################################################################################
# Bar properties
# https://felixkratz.github.io/SketchyBar/config/bar
################################################################################
bar=(
  position=top
  height=30
  color="$SKETCHY_MANTLE"
  shadow=on
)
sketchybar --bar "${bar[@]}"

################################################################################
# Item properties
# https://felixkratz.github.io/SketchyBar/config/items
################################################################################
default=(
  padding_left=2
  padding_right=2
  icon.font="Iosevka Dynamo Nerd:Bold:14.0"
  label.font="Iosevka Dynamo Nerd:Bold:22.0"
  icon.color="${SKETCHY_SUBTEXT_1}"
  label.color="${SKETCHY_SUBTEXT_1}"
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

################################################################################
# Items
################################################################################
source "${CONFIG_DIR}/items/workspaces.sh"
sketchybar --update
