[[profile]]
name = "default"

[[profile.output]]
enable = true
search = ["m=0x419D", "s=", "v=Samsung Display Corp."]
mode = "2880x1800@120Hz"
position = "0,0"
scale = 2.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "office"

[[profile.output]]
enable = true
search = ["m=", "s=", "v="]
mode = "2880x1800@60Hz"
position = "3360,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=CB242Y E", "s=24220B6C83W01", "v=Acer Technologies"]
mode = "1920x1080@60Hz"
position = "1440,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x419D", "s=", "v=Samsung Display Corp."]
mode = "2880x1800@120Hz"
position = "0,0"
scale = 2.0
transform = "normal"
adaptive_sync = false

