[tools]
gcloud = "latest"
helm = "latest"
node = "latest"
kubectl = "latest"
pre-commit = "latest"
terraform = "latest"
awscli = "latest"
uv = "latest"
python = "system"
azure = "latest"
bat = "latest"
fzf = "latest"
