[tools]
gcloud = "latest"
helm = "latest"
node = "latest"
kubectl = "latest"
pre-commit = "latest"
terraform = "latest"
awscli = "latest"
uv = "latest"
python = "system"
azure = "latest"
bat = "v0.25.0-prerelease.1"

[alias]
bat = "ubi:dynamotn/bat"
