[env]
GLAMOUR_STYLE = '~/.config/glamour/catppuccin.json'

[tools]
usage = "latest"
gcloud = "latest"
helm = "latest"
node = "latest"
kubectl = "latest"
pre-commit = "latest"
terraform = "latest"
awscli = "latest"
uv = "latest"
python = "system"
azure = "latest"
fzf = "latest"
deno = "latest"
lazygit = "latest"
go = "latest"
java = "latest"
rust = "latest"
ruby = "latest"
mkcert = "latest"
